Fixup python build system.
Signed-off-by: John Plevyak <jplevyak@gmail.com>

diff --git a/python/Makefile b/python/Makefile
--- a/python/Makefile
+++ b/python/Makefile
@@ -16,16 +16,13 @@ clean:
 	rm -rf build dparser.pyc dparser_swigc.* dparser_wrap.c swigpyrun.h \
 		tests/d_parser_mach_gen.*
 
-PYTHON_PLATLIB=$(shell $(PYTHON) -c "from distutils.command.build import build; from distutils.core import Distribution; b = build(Distribution()); b.finalize_options(); print(b.build_platlib)")
-
 TEST_SCRIPTS = $(shell ls tests/test*.py)
 test:
-ifeq ($(wildcard $(PYTHON_PLATLIB)),)
-	$(error "Unable to determine python platform library directory.")
-endif
-	@$(foreach test, $(TEST_SCRIPTS), \
+	@PLATLIB=$$($(PYTHON) -c "import glob, sysconfig, os; print(next((d for d in glob.glob('build/lib.*') if os.path.exists(os.path.join(d, '_dparser_swigc' + sysconfig.get_config_var('EXT_SUFFIX')))), ''))"); \
+	if [ -z "$$PLATLIB" ]; then echo "Unable to determine python platform library directory."; exit 1; fi; \
+	$(foreach test, $(TEST_SCRIPTS), \
 		echo "    running test $(test)" && \
-		PYTHONPATH="$(PYTHON_PLATLIB)" $(PYTHON) $(test) && \
+		PYTHONPATH="$$PLATLIB" $(PYTHON) $(test) && \
 	) echo "All unit tests passed." || \
 	( echo "At least one unit test failed."; exit 2 )
 
